const tabs = document.querySelectorAll('.tab');
const tabContents = document.querySelectorAll('.tab-content');
const maxGalleryPhotos = 26;
const bookStates = { gallery: { spreads: [], currentSpreadIndex: 0, isTurning: false, bookPagesId: 'book-pages', prevButtonId: 'prev-page', nextButtonId: 'next-page', pageTurnerId: '.page-turner', dataSource: () => window.galleryFiles || [] }, presentesDante: { spreads: [], currentSpreadIndex: 0, isTurning: false, bookPagesId: 'book-pages-dante', prevButtonId: 'prev-page-dante', nextButtonId: 'next-page-dante', pageTurnerId: '#page-turner-dante', dataSource: () => window.presentesDantePd || [] }, presentesDuda: { spreads: [], currentSpreadIndex: 0, isTurning: false, bookPagesId: 'book-pages-duda', prevButtonId: 'prev-page-duda', nextButtonId: 'next-page-duda', pageTurnerId: '#page-turner-duda', dataSource: () => window.presentesDudaPd || [] } };
function updateTabs() { tabs.forEach(tab => { const target = tab.dataset.tab;
const section = document.getElementById(target);
tab.classList.toggle('active', section && section.classList.contains('active'));
});
} function refreshSpreads(bookKey) { const bookPages = document.getElementById(bookStates[bookKey].bookPagesId);
bookStates[bookKey].spreads = Array.from(bookPages.querySelectorAll('.page-spread'));
} function setActiveSpread(bookKey, index) { refreshSpreads(bookKey);
const state = bookStates[bookKey];
const prevBtn = document.getElementById(state.prevButtonId);
const nextBtn = document.getElementById(state.nextButtonId);
state.spreads.forEach((spread, i) => { spread.classList.toggle('active', i === index);
});
prevBtn.disabled = index === 0;
nextBtn.disabled = index === state.spreads.length - 1;
} function createGalleryPage(positionClass, src, label, hasImage = true) { const page = document.createElement('div');
page.className = `page ${positionClass}`;
const content = document.createElement('div');
content.className = 'page-content';
if (hasImage) { const image = new Image();
image.src = src;
image.alt = `Foto ${label}`;
image.className = 'page-image';
image.onload = () => { content.textContent = '';
content.appendChild(image);
};
image.onerror = () => { content.textContent = '';
};
content.innerHTML = '<span class="page-placeholder">Carregando...</span>';
} else { content.textContent = '';
} page.appendChild(content);
return page;
} function buildSpreads(bookKey) { const state = bookStates[bookKey];
const bookPages = document.getElementById(state.bookPagesId);
bookPages.innerHTML = '';
const imageSources = state.dataSource().slice(0, maxGalleryPhotos);
const spreadCount = Math.max(1, Math.ceil(imageSources.length / 2));
for (let i = 0;
i < spreadCount;
i++) { const spread = document.createElement('div');
spread.className = 'page-spread';
spread.dataset.spread = i;
const leftIndex = i * 2;
const rightIndex = i * 2 + 1;
const leftSrc = imageSources[leftIndex];
const rightSrc = imageSources[rightIndex];
const leftPage = leftSrc ? createGalleryPage('left-page', leftSrc, leftIndex + 1) : createGalleryPage('left-page', '', leftIndex + 1, false);
const rightPage = rightSrc ? createGalleryPage('right-page', rightSrc, rightIndex + 1) : createGalleryPage('right-page', '', rightIndex + 1, false);
spread.appendChild(leftPage);
spread.appendChild(rightPage);
bookPages.appendChild(spread);
} refreshSpreads(bookKey);
state.currentSpreadIndex = 0;
setActiveSpread(bookKey, state.currentSpreadIndex);
} function turnPage(bookKey, direction) { const state = bookStates[bookKey];
if (state.isTurning) return;
const nextIndex = direction === 'next' ? state.currentSpreadIndex + 1 : state.currentSpreadIndex - 1;
if (nextIndex < 0 || nextIndex >= state.spreads.length) return;
state.isTurning = true;
const pageTurner = document.querySelector(state.pageTurnerId);
const turnClass = direction === 'next' ? 'flip-next' : 'flip-prev';
const oppositeClass = direction === 'next' ? 'flip-prev' : 'flip-next';
pageTurner.classList.remove(oppositeClass);
pageTurner.classList.add('active', turnClass);
setTimeout(() => { pageTurner.classList.remove('active', turnClass);
state.currentSpreadIndex = nextIndex;
setActiveSpread(bookKey, state.currentSpreadIndex);
state.isTurning = false;
}, 580);
} function setupBook(bookKey) { const state = bookStates[bookKey];
const bookPages = document.getElementById(state.bookPagesId);
const prevBtn = document.getElementById(state.prevButtonId);
const nextBtn = document.getElementById(state.nextButtonId);
if (!bookPages || !prevBtn || !nextBtn) return;
prevBtn.addEventListener('click', () => turnPage(bookKey, 'prev'));
nextBtn.addEventListener('click', () => turnPage(bookKey, 'next'));
bookPages.addEventListener('click', () => { if (bookKey === 'gallery' && document.getElementById('galeria').classList.contains('active')) { turnPage(bookKey, 'next');
} else if ((bookKey === 'presentesDante' || bookKey === 'presentesDuda') && document.getElementById('presente').classList.contains('active')) { turnPage(bookKey, 'next');
} });
buildSpreads(bookKey);
} tabs.forEach(tab => { tab.addEventListener('click', () => { const target = tab.dataset.tab;
tabs.forEach(t => t.classList.remove('active'));
tab.classList.add('active');
tabContents.forEach(section => { section.classList.toggle('active', section.id === target);
});
updateTabs();
});
});
setupBook('gallery');
setupBook('presentesDante');
setupBook('presentesDuda');
updateTabs();
const imageModal = document.getElementById('image-modal');
const modalImage = document.getElementById('modal-image');
const modalClose = document.querySelector('.modal-close');
function openImageModal(imageSrc) { modalImage.src = imageSrc;
imageModal.classList.add('active');
document.body.style.overflow = 'hidden';
} function closeImageModal() { imageModal.classList.remove('active');
document.body.style.overflow = 'auto';
} modalClose.addEventListener('click', closeImageModal);
imageModal.addEventListener('click', (e) => { if (e.target === imageModal) { closeImageModal();
} });
document.addEventListener('keydown', (e) => { if (e.key === 'Escape' && imageModal.classList.contains('active')) { closeImageModal();
} });
document.addEventListener('click', (e) => { if (e.target.classList.contains('page-image')) { openImageModal(e.target.src);
} });